account/urls.py
from . import views
from django.urls import path

app_name, urlpatterns = "account", [
    path("signup/", views.signup_view, name="signup-view"),
    path("signin/", views.signin_view, name="signin-view"),
    path("signout/", views.signout_view, name="signout-view"),
]

landing/urls.py
from . import views
from django.urls import path

app_name, urlpatterns = "landing", [
    path("category/<id>/", views.category_detail_view, name="category-detail-view"),
    path("category/", views.category_view, name="category-view"),
    path("contact/", views.contact_view, name="contact-view"),
    path("<id>/", views.detail_view, name="detail-view"),
    path("about/", views.about_view, name="about-view"),
    path("", views.index_view, name="index-view"),
]

website/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("account.urls")),
    path("", include("landing.urls")),
    path("__reload__/", include("django_browser_reload.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

account/models.py
from django.db import models
from django.contrib.auth import get_user_model

User = get_user_model()


class Contact(models.Model):
    message = models.TextField()
    name = models.CharField(max_length=255)
    phone = models.CharField(max_length=255)
    email = models.EmailField(max_length=255)
    updated_at = models.DateTimeField(auto_now=True)
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ["-created_at"]

    def __str__(self):
        return f"{self.name} - {self.email}"


class Purchase(models.Model):
    to_date = models.DateField()
    buyer = models.ForeignKey(User, models.PROTECT)
    from_date = models.DateField(auto_now_add=True)
    apartment = models.ForeignKey("landing.apartment", models.CASCADE)
    total_price = models.DecimalField(decimal_places=2, max_digits=10)

landing/models.py
from django.db import models
from django.contrib.auth import get_user_model


User = get_user_model()


class Category(models.Model):
    updated_at = models.DateTimeField(auto_now=True)
    created_at = models.DateTimeField(auto_now_add=True)
    name = models.CharField(max_length=255, unique=True)

    class Meta:
        ordering = ["name"]
        verbose_name_plural = "categories"

    def __str__(self) -> str:
        return self.name.title()


class Apartment(models.Model):
    name = models.CharField(max_length=255)
    description = models.TextField(default="")
    owner = models.ForeignKey(User, models.PROTECT)
    updated_at = models.DateTimeField(auto_now=True)
    created_at = models.DateTimeField(auto_now_add=True)
    category = models.ForeignKey(Category, models.PROTECT)
    price = models.DecimalField(decimal_places=2, max_digits=10)
    current = models.ForeignKey(
        User, models.SET_NULL, related_name="+", null=True, blank=True
    )

    class Meta:
        ordering = ["-created_at"]

    def __str__(self) -> str:
        return self.name.title()


class Image(models.Model):
    image = models.ImageField(upload_to="images")
    apartment = models.ForeignKey(Apartment, models.CASCADE)

    def __str__(self) -> str:
        return f"{self.apartment}'s {self.id} image"

account/forms.py
from . import models
from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm


class RegisterForm(UserCreationForm):
    class Meta:
        model = get_user_model()
        fields = [
            "email",
            "username",
            "password1",
            "password2",
            "last_name",
            "first_name",
        ]


class ContactForm(forms.ModelForm):
    class Meta:
        model = models.Contact
        fields = ["name", "email", "phone", "message"]


class PurchaseForm(forms.ModelForm):
    class Meta:
        model = models.Purchase
        fields = ["to_date", "apartment", "buyer", "total_price"]

landing/forms.py
from . import models
from django import forms


class CategoryForm(forms.ModelForm):
    class Meta:
        fields = ["name"]
        model = models.Category


class apartmentForm(forms.ModelForm):
    class Meta:
        model = models.Apartment
        fields = ["name", "category", "price", "owner"]


class ImageForm(forms.ModelForm):
    class Meta:
        model = models.Image
        fields = ["image", "apartment"]

account/views.py
from . import forms
from django.contrib import auth, messages
from django.shortcuts import render, redirect
from django.contrib.auth.models import Group, User


def signout_view(request):
    auth.logout(request)
    return redirect(request.GET.get("next", "/"))


def signup_view(request):
    if request.method == "POST":
        role = request.POST.get("role")
        form = forms.RegisterForm(request.POST)

        if form.is_valid():
            user: User = form.save()

            group, _ = Group.objects.get_or_create(name=role)
            user.groups.add(group)

            messages.success(request, "Account created successfully")
            return redirect("account:signin-view")

        [messages.error(request, i[0]) for i in form.errors.values()]
        return redirect("account:signup-view")

    return render(request, "account/signup.html")


def signin_view(request):
    if request.method == "POST":
        user = auth.authenticate(
            request,
            username=request.POST.get("username"),
            password=request.POST.get("password"),
        )

        if user:
            auth.login(request, user)
            return redirect("landing:index-view")

        messages.error(request, "Invalid credentials")
        return redirect("account:signin-view")

    return render(request, "account/signin.html")

landing/views.py
from . import models
from django.contrib import messages
from account.models import Purchase
from account.forms import ContactForm
from django.shortcuts import render, redirect
from django.utils.timezone import datetime, timedelta
from django.contrib.auth.decorators import login_required


def about_view(request):
    return render(request, "landing/about.html")


def index_view(request):
    apartments = models.Apartment.objects.filter(current__isnull=True)[:9]

    context = {"apartments": apartments}
    return render(request, "landing/index.html", context)


def category_view(request):
    categories = models.Category.objects.all()

    context = {"categories": categories}
    return render(request, "category/index.html", context)


def category_detail_view(request, id):
    category = models.Category.objects.get(id=id)
    apartments = category.apartment_set.filter(current__isnull=True)

    context = {"apartments": apartments, "category": category}
    return render(request, "category/detail.html", context)


@login_required
def detail_view(request, id):
    if request.method == "POST":
        apartment = request.POST.get("apartment")
        month_count = int(request.POST.get("month", 0))

        if month_count:
            apartment = models.Apartment.objects.get(id=id)
            to_date = datetime.now() + timedelta(days=30 * month_count)

            apartment.current = request.user
            Purchase.objects.create(
                apartment=apartment,
                to_date=to_date,
                buyer=request.user,
                total_price=apartment.price * month_count,
            )
            apartment.save()

            messages.success(
                request, f"Apartment rented successfully for {month_count} months"
            )
            return redirect("landing:index-view")

    apartment = models.Apartment.objects.get(id=id)
    if apartment.current:
        messages.warning(request, "The apartment is already rented")
        return redirect("landing:index-view")

    context = {"apartment": apartment}
    return render(request, "landing/detail.html", context)


def contact_view(request):
    if request.method == "POST":
        form = ContactForm(request.POST)

        if form.is_valid() and form.save():
            messages.success(request, "Message sent successfully")
        else:
            messages.error(request, "Message not sent")

        return redirect("landing:contact-view")

    return render(request, "landing/contact.html")

account/templates/account.html
{% load static tailwind_tags %}
<!DOCTYPE html>
<html lang="en">
  <head>
    {% tailwind_css %}
    <meta charset="UTF-8" />
    <title>Authentication</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  </head>
  <body class="w-screen h-screen relative flex items-center justify-center bg-slate-200 overflow-hidden">
    <div class="absolute rounded-full aspect-1 bottom-14 -right-20 w-full md:w-2/3 from-indigo-400 to-slate-800 bg-gradient-to-br flex items-center justify-center shadow-md"></div>
    <header class="fixed top-0 left-0 w-screen p-3 px-[5%] flex items-center justify-between z-10">
      <a href="{% url 'landing:index-view' %}" class="capitalize font-bold text-xl absolute md:relative left-1/2 md:left-auto -translate-x-1/2 md:translate-x-0"><span class="text-xl text-slate-600 font-bold">E</span>state</a>

      <nav class="flex grow items-center justify-between md:justify-end gap-4 text-slate-700 md:text-slate-200 drop-shadow-lg text-xs md:text-base" style="font-variant: small-caps;">
        <a href="{% url 'landing:about-view' %}" class="current transition-all hover:text-slate-800">about us</a>
        <a href="{% url 'landing:contact-view' %}" class="current transition-all hover:text-slate-800">contact us</a>
      </nav>
    </header>
    <main class="p-2 backdrop-blur-md bg-white bg-opacity-40 rounded-md">
      {% block content %}

      {% endblock %}
    </main>
    {% include 'components/messages.html' %}
  </body>
</html>

landing/templates/category/detail.html
{% extends 'landing.html' %}

{% block content %}
  <section class="w-4/6 rounded-full p-10 flex items-center justify-center bg-slate-600 text-white font-bold py-10 mt-24 mx-auto">
    <h2 style="font-variant: small-caps;" class="text-center text-4xl">{{ category.name }}</h2>
  </section>

  <section class="w-full grid gap-6 px-[10%] grid-cols-[repeat(auto-fill,minmax(20rem,1fr))]">
    {% for apartment in apartments %}
      <div class="h-80 bg-slate-700 relative overflow-hidden group cursor-pointer">
        <img src="{{ apartment.image_set.first.image.url }}" alt="" class="w-full h-full object-cover" />
        <div class="top-0 left-0 absolute w-full h-full bg-black scale-110 bg-opacity-60 opacity-0 transition-all group-hover:scale-100 group-hover:opacity-100 flex flex-col items-center justify-end pb-[15%] text-white">
          <a href="{% url 'landing:category-detail-view' apartment.category.id %}" style="font-variant: small-caps;" class="text-sm lowercase">{{ apartment.category.name }}</a>
          <a href="{% url 'landing:detail-view' apartment.id %}" class="text-xl capitalize font-semibold">{{ apartment.name }}</a>
        </div>
      </div>
    {% endfor %}
  </section>
{% endblock %}

landing/templates/category/index.html
{% extends 'landing.html' %}

{% block content %}
  <section class="w-4/6 rounded-full p-10 flex items-center justify-center bg-slate-600 text-white font-bold py-10 mt-24 mx-auto">
    <h2 style="font-variant: small-caps;" class="text-center text-4xl">categories</h2>
  </section>

  <section class="w-full px-[10%] grid gap-10 grid-cols-[repeat(auto-fill,minmax(20rem,1fr))]">
    {% for category in categories %}
      <div class="h-10 flex group items-center overflow-hidden shadow-md rounded-md p-2 pl-4 relative before:left-0 before:absolute before:h-full before:w-1 before:bg-slate-600 before:transition-all hover:before:w-full">
        <a href="{% url 'landing:category-detail-view' category.id %}" class="z-10 font-semibold transition-all group-hover:text-white">{{ category.name }}</a>
      </div>
    {% endfor %}
  </section>
{% endblock %}

landing/templates/landing.html
{% load static heroicons tailwind_tags %}
<!DOCTYPE html>
<html lang="en">
  <head>
    {% tailwind_css %}
    <title>Leaftip</title>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  </head>
  <body class="w-screen overflow-x-hidden flex flex-col items-center">
    <header style="font-variant: small-caps;" class="p-3 z-50 px-[10%] md:px-[4%] fixed top-0 left-0 md:left-auto md:top-4 w-full md:w-4/6 flex items-center justify-between bg-white md:bg-opacity-80 md:backdrop-blur-md md:rounded shadow-md text-xs font-semibold text-blue-400">
      <a href="{% url 'landing:index-view' %}" class=""><span class="text-xl text-blue-600 font-bold">E</span>state</a>

      <nav class="hidden md:flex grow items-center justify-center gap-4">
        <a href="{% url 'landing:about-view' %}" class="current transition-all hover:text-blue-800">about us</a>
        <a href="{% url 'landing:category-view' %}" class="current transition-all hover:text-blue-800">categories</a>
        <a href="{% url 'landing:contact-view' %}" class="current transition-all hover:text-blue-800">contact us</a>
      </nav>

      <nav class="flex items-center justify-center">
        {% if user.is_authenticated %}
          <a href="{% url 'account:signout-view' %}" class="px-5 py-0.5 ml-4 text-white bg-blue-600 rounded-full">sign out</a>
        {% else %}
          <a href="{% url 'account:signin-view' %}" class="transition-all hover:text-slate-800">sign in</a>
          <a href="{% url 'account:signup-view' %}" class="px-5 py-0.5 ml-4 text-white bg-blue-600 rounded-full">sign up</a>
        {% endif %}
      </nav>
    </header>

    <main class="grow w-full flex flex-col min-h-screen mb-10 gap-10">
      {% block content %}

      {% endblock %}
    </main>

    <footer class="w-full p-10 bg-black"></footer>

    <nav class="w-full sticky bg-white text-blue-500 gap-4 bottom-0 py-2 font-semibold flex md:hidden items-center justify-evenly px-[10%] text-xs" style="font-variant: small-caps;">
      <a href="{% url 'landing:about-view' %}" class="flex flex-col items-center transition-all hover:text-blue-800">
        <i class="scale-75 -mb-1">{% heroicon_outline 'question-mark-circle' %}</i>
        <span class="">about us</span>
      </a>
      <a href="{% url 'landing:contact-view' %}" class="flex flex-col items-center transition-all hover:text-blue-800">
        <i class="scale-75 -mb-1">{% heroicon_outline 'chat-bubble-left-ellipsis' %}</i>
        <span class="">contact us</span>
      </a>
    </nav>

    {% include 'components/messages.html' %}
  </body>
  <script>
    document.querySelectorAll('a.current').forEach((el) => {
      if (location.href == el.href) el.classList.add('text-blue-800')
    })
  </script>
  {% block script %}

  {% endblock %}
</html>

landing/templates/landing/about.html
{% extends 'landing.html' %}

{% block content %}
  <section class="w-full bg-blue-900 brightness-75 text-white font-bold flex items-center justify-center aspect-[3.5] min-h-80">
    <h1 class="capitalize text-3xl md:text-6xl">who we are</h1>
  </section>

  <section class="w-full flex flex-wrap gap-8 px-[10%]">
    <div class="h-80 basis-96 grow flex flex-col items-start justify-center gap-4 p-[5%] shadow from-blue-400 to-blue-800 bg-gradient-to-b"></div>

    <div class="h-80 basis-96 grow flex flex-col items-start justify-center gap-4 p-[5%] shadow">
      <h2 class="capitalize self-center md:self-start text-2xl md:text-4xl">our vision</h2>
      <p class="font-thin">
        {% lorem 50 w %}
      </p>
    </div>

    <div class="h-80 basis-96 grow flex flex-col items-center justify-center gap-4 p-[5%] shadow">
      <h2 class="capitalize text-2xl md:text-4xl">our vision</h2>
      <p class="text-center font-thin">
        {% lorem 50 w %}
      </p>
    </div>
  </section>
{% endblock %}

landing/templates/landing/contact.html
{% extends 'landing.html' %}
{% load heroicons %}

{% block content %}
  <section class="w-full flex flex-wrap gap-10 px-[15%] pt-28">
    <div class="basis-60 grow rounded-flex flex-col p-4 bg-gray-200"></div>
    <div class="basis-80 grow-[3]">
      <form action="" method="post" class="w-full h-full flex gap-5 flex-col items-center relative rounded p-8 bg-white bg-opacity-90 backdrop-blur">
        {% csrf_token %}
        <h2 class="capitalize lg:text-2xl font-bold text-blue-700">send your message</h2>

        <div class="flex flex-wrap gap-4 w-full">
          <div class="flex flex-col basis-72 grow">
            <label htmlFor="" class="capitalize font-serif text-gray-500">name</label>
            <div class="relative items-center w-full flex border p-1 gap-1 pl-2 border-blue-400 rounded">
              <span class="scale-75 text-gray-600">{% heroicon_outline 'pencil' %}</span>
              <input required name="name" type="text" class="p-1 px-2 w-full border-none outline-none bg-transparent text-blue-500 resize-none" autoComplete="off" />
            </div>
          </div>

          <div class="flex flex-col basis-72 grow">
            <label htmlFor="" class="capitalize font-serif text-gray-500">email</label>
            <div class="relative items-center w-full flex border p-1 gap-1 pl-2 border-blue-400 rounded">
              <span class="scale-75 text-gray-600">{% heroicon_outline 'at-symbol' %}</span>
              <input required name="email" type="email" class="p-1 px-2 w-full border-none outline-none bg-transparent text-blue-500 resize-none" autoComplete="off" />
            </div>
          </div>

          <div class="flex flex-col basis-72 grow">
            <label htmlFor="" class="capitalize font-serif text-gray-500">phone number</label>
            <div class="relative items-center w-full flex border p-1 gap-1 pl-2 border-blue-400 rounded">
              <span class="scale-75 text-gray-600">{% heroicon_outline 'pencil' %}</span>
              <input required name="phone" type="tel" class="p-1 px-2 w-full border-none outline-none bg-transparent text-blue-500 resize-none" autoComplete="off" />
            </div>
          </div>

          <div class="flex flex-col basis-72 grow">
            <label htmlFor="" class="capitalize font-serif text-gray-500">message</label>
            <div class="relative items-center w-full flex border p-1 gap-1 pl-2 border-blue-400 rounded">
              <span class="scale-75 text-gray-600 mb-auto">{% heroicon_outline 'chat-bubble-left' %}</span>
              <textarea required name="message" class="p-1 px-2 w-full border-none outline-none resize-none h-20 bg-transparent text-blue-500 resize-none" autoComplete="off"></textarea>
            </div>
          </div>
        </div>

        <button class="py-2 w-full uppercase mr-auto text-white bg-blue-700 transition-all hover:brightness-110">message us</button>
      </form>
    </div>
  </section>
{% endblock %}

landing/templates/landing/detail.html
{% extends 'landing.html' %}

{% block content %}
  <section class="mt-20 w-full flex flex-col items-center justify-center gap-2">
    <a href="{% url 'landing:category-detail-view' apartment.category.id %}" class="text-xs text-gray-400" style="font-variant: small-caps;">{{ apartment.category.name }}</a>
    <h2 class="text-3xl font-serif text-slate-600 font-semibold text-center">{{ apartment.name }}</h2>
  </section>

  <section class="w-full grid gap-6 px-[10%] grid-cols-[repeat(auto-fit,minmax(20rem,1fr))]">
    <div class="shadow-md flex flex-col min-h-60 gap-4">
      <img id="image" src="{{ apartment.image_set.first.image.url }}" alt="" class="w-full aspect-2 object-contain bg-gray-100" />
      <div class="flex-none w-full h-20 bg-slate-200 p-2 lfex items-center justify-start gap-2 overflow-auto">
        {% for image in apartment.image_set.all %}
          <img src="{{ image.image.url }}" alt="" class="images cursor-pointer h-full object contain rounded-md" />
        {% endfor %}
      </div>
    </div>

    <div class="flex flex-col gap-4 min-h-60 p-4">
      <div class="w-full flex items-center justify-start gap-2 text-slate-600">
        <span class="text-lg" style="font-variant: small-caps;">price: <i class="">N{{ apartment.price }}, per month</i></span>
      </div>

      <div class="w-full flex flex-col gap-1">
        <p class="text-sm text-justify">{{ apartment.description }}</p>
      </div>

      <form id="request-form" method="post" class="w-full flex items-center mt-auto justify-start gap-2">
        {% csrf_token %}
        <div class="flex items-center justify-start gap-4">
          <span>number of months</span>
          <input id="count" type="number" name="month" min="1" value="0" class="w-20 h-8" onchange="document.querySelector('#total').textContent = 'N '+event.target.value*{{ apartment.price }}" />
          <output id="total">N 0.00</output>
        </div>
        <button style="font-variant: small-caps;" class="ml-auto text-sm bg-slate-600 text-white rounded px-6 py-1">purchase</button>
      </form>
    </div>
  </section>
{% endblock %}

{% block script %}
  <script src="https://js.paystack.co/v1/inline.js"></script>
  <script>
    let image = document.querySelector('#image')
    document.querySelectorAll('.images').forEach((img) => {
      img.onclick = () => (image.src = img.src)
    })
  </script>
  <script>
    document.addEventListener('DOMContentLoaded', () => {
      const form = document.querySelector('#request-form')
    
      form.addEventListener('submit', handleFormSubmit)
    
      function handleFormSubmit(ev) {
        ev.preventDefault()
    
        let tag = document.querySelector('#count')
        if (tag.value == 0) return
    
        let handler = PaystackPop.setup({
          currency: 'NGN',
          email: '{{ user.email }}',
          ref: '' + Math.floor(Math.random() * 1000000000 + 1), // generates a pseudo-unique reference. Please replace with a reference you generated. Or remove the line entirely so our API will generate one for you
          key: 'pk_test_3288357263a2a6e7b787f4fa87e4642e31819a1b', // Replace with your public key
          amount: Number('{{apartment.price}}') * Number(tag.value) * 100,
          onClose: function () {
            alert('You have canceled the transaction')
          },
          callback: function () {
            form.submit()
          }
        })
    
        handler.openIframe()
      }
    })
  </script>
{% endblock %}

landing/templates/landing/index.html
{% extends 'landing.html' %}
{% load static %}

{% block content %}
  <section class="w-full relative aspect-[2.4] min-h-96 bg-slate-700">
    {% comment %} <img src="{% static 'images/train-banner.jpg' %}" alt="" class="w-full h-full absolute brightness-75 object-cover rounded-md" /> {% endcomment %}

    <div class="w-full h-full font-bold relative flex flex-col items-center justify-end gap-2 p-[10%] pb-[12%] text-white">
      <h3 class="text-xl md:text-3xl capitalize">e-state management</h3>
      <h2 class="text-2xl md:text-5xl uppercase">get the most astonishing one</h2>
    </div>
  </section>

  <section class="w-full flex flex-col">
    <h2 class="text-capitalize text-center text-3xl" style="font-variant: small-caps;">our most recent apartments</h2>

    <div class="w-full flex flex-col gap-6 px-[5%]"></div>
  </section>

  <section class="w-full grid gap-6 px-[10%] grid-cols-[repeat(auto-fill,minmax(20rem,1fr))]">
    {% for apartment in apartments %}
      <div class="h-80 bg-slate-700 relative overflow-hidden group cursor-pointer">
        <img src="{{ apartment.image_set.first.image.url }}" alt="" class="w-full h-full object-cover" />
        <div class="top-0 left-0 absolute w-full h-full bg-black scale-110 bg-opacity-60 opacity-0 transition-all group-hover:scale-100 group-hover:opacity-100 flex flex-col items-center justify-end pb-[15%] text-white">
          <a href="{% url 'landing:category-detail-view' apartment.category.id %}" style="font-variant: small-caps;" class="text-sm lowercase">{{ apartment.category.name }}</a>
          <a href="{% url 'landing:detail-view' apartment.id %}" class="text-xl capitalize font-semibold">{{ apartment.name }}</a>
        </div>
      </div>
    {% endfor %}
  </section>

  <section class="w-full p-4 px-[10%]">
    <div class="w-full flex flex-col gap-4 items-center justify-center text-white text-center font-semibold aspect-3 min-h-40 relative from-blue-400 to-blue-800 bg-gradient-to-b rounded-md">
      <h2 class="text-xl md:text-3xl w-5/6">choose your desire apartment</h2>
    </div>
  </section>
{% endblock %}

theme/templates/base.html
{% load static tailwind_tags %}
<!DOCTYPE html>
<html lang="en">
	<head>
    <title>Django Tailwind</title>
		<meta charset="UTF-8">
		<meta name="viewport" content="width=device-width, initial-scale=1.0">
		<meta http-equiv="X-UA-Compatible" content="ie=edge">
		{% tailwind_css %}
	</head>

	<body class="bg-gray-50 font-serif leading-normal tracking-normal">
		<div class="container mx-auto">
			<section class="flex items-center justify-center h-screen">
				<h1 class="text-5xl">Django + Tailwind = ❤️</h1>
			</section>
		</div>
	</body>
</html>

website/templates/components/messages.html
{% load static tailwind_tags %}
{% tailwind_css %}

{% if messages %}
  <style>
    #errors {
      .error {
        --bg: rgb(182, 48, 48);
      }
      .warning {
        --bg: rgb(224, 163, 31);
      }
      .success {
        --bg: rgb(78, 239, 78);
      }
    }
  </style>
  <section id="errors" class="w-screen h-screen top-0 left-0 fixed z-50 pointer-events-none p-10 flex flex-col {{ flex|default:'items-end justify-end' }} gap-4">
    {% for message in messages %}
      <span style="--w: 100%;" class="{{ message.tags }} w-80 p-3 bg-white text-sm text-[var(--bg)] translate-x-full transition-all shadow-md pointer-events-auto cursor-pointer opacity-0 relative overflow-x-hidden before:absolute before:left-0 before:bottom-0 before:w-[var(--w)] before:h-0.5 before:bg-[var(--bg)] before:transition-all">{{ message }}</span>
    {% endfor %}
  </section>

  <script>
    document.querySelectorAll('#errors span').forEach((message, id, messages) => {
      let [count, decrement, interval] = [100, 1]
    
      setTimeout(() => {
        message.style.opacity = 1
        message.style.transform = 'translateX(0)'
        interval = setInterval(() => {
          count -= decrement
          message.style.setProperty('--w', `${count}%`)
          if (count <= 0) clearInterval(interval), message.remove()
        }, 40 + 5 * (messages.length - id))
      }, 900 + 800 * id)
    
      message.addEventListener('mouseout', () => (decrement = 1))
      message.addEventListener('mouseover', () => (decrement = 0))
      message.addEventListener('click', () => message.remove(), clearInterval(interval))
    })
  </script>
{% endif %}